"""Delivery QA for full-sequence target review and frozen-target SAR gate."""
from pathlib import Path
import json
from playwright.sync_api import sync_playwright
W=Path('D:/profile/research/workspace'); O=W/'output/tpgt/unified_target_review_observation'; A=O/'audit'; A.mkdir(parents=True,exist_ok=True)
out={'kind':'TPGT_UNIFIED_TARGET_REVIEW_DELIVERY_QA','checks':[]}
with sync_playwright() as pw:
    b=pw.chromium.launch(executable_path='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless=True)
    c=b.new_context(viewport={'width':1450,'height':1000})
    page=c.new_page(); page.goto('http://127.0.0.1:8780/workspace/output/tpgt/unified_target_review_observation/index.html'); assert page.locator('a').count()>=5
    # CAR: proposal stays separate from the manually entered interval and freeze gate.
    page.goto('http://127.0.0.1:8780/workspace/output/tpgt/unified_target_review_observation/TARGET_REVIEW_VIEW.html?target=CAR%3AGM_RM017%3APV002'); page.wait_for_function("document.querySelector('#optical').naturalWidth>0"); page.locator('#frameInput').fill('367'); page.locator('#jump').click(); assert '367' in page.locator('#frameInfo').inner_text(); page.locator('#sourceToggle').check(); page.locator('#proposalToggle').check(); page.locator('#detectorToggle').check(); page.wait_for_timeout(100); assert page.locator('#sarLink').is_hidden()
    assert page.locator('#humanBand').is_hidden(); page.locator('#visibleStart').fill('145'); page.locator('#visibleEnd').fill('190'); page.locator('#coreStart').fill('154'); page.locator('#coreEnd').fill('173'); page.locator('#humanId').fill('GM_RM017:HUMAN_CAR_001'); page.locator('#targetType').select_option('CAR'); page.locator('#bodyCompleteness').select_option('COMPLETE'); page.locator('#boundaryState').select_option('INTERIOR'); page.locator('#identityStatus').select_option('CLEAR'); page.locator('#saveInterval').click(); page.locator('#saveReview').click(); page.wait_for_timeout(150); assert 'r1' in page.locator('#reviewHistory').inner_text(); page.locator('#freeze').click(); page.wait_for_timeout(150); assert not page.locator('#sarLink').is_hidden(); frozen=page.evaluate("JSON.parse(localStorage.getItem('TPGT_TARGET_REVIEW_CAR:GM_RM017:PV002')).frozen"); assert frozen['core_interval']==[154,173]
    # Revision after freeze does not overwrite freeze record.
    page.locator('#reviewNote').fill('post-freeze note'); page.locator('#saveReview').click(); page.wait_for_timeout(100); frozen2=page.evaluate("JSON.parse(localStorage.getItem('TPGT_TARGET_REVIEW_CAR:GM_RM017:PV002')).frozen"); assert frozen2['freeze_id']==frozen['freeze_id']
    page.goto('http://127.0.0.1:8780/workspace/output/tpgt/unified_target_review_observation/SAR_OBSERVATION_VIEW.html?target=CAR%3AGM_RM017%3APV002'); page.wait_for_function("!document.querySelector('#app').classList.contains('hidden')"); assert 'FROZEN' in page.locator('#gate').inner_text(); page.locator('#frame').fill('154'); page.locator('#frame').dispatch_event('input'); page.wait_for_timeout(120); page.locator('#addRect').click(); box=page.locator('#marks').bounding_box(); page.mouse.move(box['x']+80,box['y']+80); page.mouse.down(); page.mouse.move(box['x']+180,box['y']+150); page.mouse.up(); page.locator('#save').click(); page.wait_for_timeout(100); assert 'PRE_OPEN_BOOK' in page.locator('#status').inner_text()
    # PERSON full stream exposes detector activity and does not auto-promote a provisional identity.
    p=c.new_page(); p.goto('http://127.0.0.1:8780/workspace/output/tpgt/unified_target_review_observation/TARGET_REVIEW_VIEW.html?target=PERSON%3AGM_RM017%3AFULL_SEQUENCE'); p.wait_for_function("document.querySelector('#optical').naturalWidth>0"); p.locator('#detectorToggle').check(); p.locator('#identityToggle').check(); p.wait_for_timeout(100); assert p.locator('#detBands .detector').count()>0; assert p.locator('#humanId').input_value()==''; assert p.locator('#sarLink').is_hidden(); p.close()
    out['checks']=[{'full_optical_stream_0_367':'PASS','overlay_on_off':'PASS','proposal_separate_from_human_interval':'PASS','human_interval_save_reload':'PASS','freeze_revision_immutable':'PASS','frozen_target_enters_sar':'PASS','unfrozen_gate':'PASS','person_detector_activity_without_identity_promotion':'PASS','pre_open_book_observation':'PASS'}]; b.close()
out['complete']=True;(A/'unified_workbench_qa.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8'); print(json.dumps(out,ensure_ascii=False))
