(function(){
  'use strict';
  const D=window.TPGT_WORKBENCH_DATA, mode=document.body.dataset.viewMode||'BLIND_OBSERVATION';
  if(!D) throw Error('missing TPGT_WORKBENCH_DATA');
  const $=id=>document.getElementById(id), storage='TPGT_PHASE1A_OBS_'+D.event_hypothesis_id;
  let si=0,oi=0,timer=null,draw=null, refs=null;
  const morphology=['POINT_LIKE','COMPACT_REGION','ELONGATED_REGION','BAND_LIKE','MULTI_COMPONENT','DIFFUSE_REGION','BOUNDARY_ATTACHED','UNCLEAR','OTHER'];
  const transitions=['APPEAR','DISAPPEAR','SHIFT','ELONGATE','CONTRACT','SPLIT','MERGE','DOMINANT_SWITCH','DISPLAY_BRIGHTNESS_INCREASE','DISPLAY_BRIGHTNESS_DECREASE','INTERMITTENT','NO_CLEAR_CHANGE','UNCERTAIN','OTHER'];
  const read=()=>{try{return JSON.parse(localStorage.getItem(storage)||'{"revisions":[],"marks":[],"bookmarks":[]}')}catch(_){return {revisions:[],marks:[],bookmarks:[]}}}; let state=read();
  function saveLocal(){localStorage.setItem(storage,JSON.stringify(state));}
  function checked(id){return [...document.querySelectorAll('#'+id+' input:checked')].map(x=>x.value)}
  function choices(id,values){const e=$(id);if(!e)return; e.innerHTML=values.map(v=>`<label><input type="checkbox" value="${v}"> ${v}</label>`).join('');}
  choices('morphology',morphology);choices('transitions',transitions);
  function nativePoint(ev,canvas){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(D.sar_width,(ev.clientX-r.left)*D.sar_width/r.width)),y:Math.max(0,Math.min(D.sar_height,(ev.clientY-r.top)*D.sar_height/r.height))}}
  function fitCanvas(canvas,w,h){canvas.width=w;canvas.height=h;canvas.style.width='100%';canvas.style.height='100%'}
  function image(src){return new Promise((ok,fail)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=fail;i.src=src})}
  function clearCanvas(c){c.getContext('2d').clearRect(0,0,c.width,c.height)}
  function drawBoxes(c,boxes,style){const g=c.getContext('2d');g.strokeStyle=style;g.lineWidth=Math.max(2,c.width/600);for(const b of boxes){if(b.geometry_type==='POINT'){g.fillStyle=style;g.beginPath();g.arc(b.x,b.y,6,0,Math.PI*2);g.fill()}else{g.strokeRect(b.x1,b.y1,b.x2-b.x1,b.y2-b.y1)}}}
  async function render(){const sr=D.sar[si],t=sr.t-(+$('offset')?.value||0);oi=D.optical.reduce((best,x,i)=>Math.abs(x.t-t)<Math.abs(D.optical[best].t-t)?i:best,0);const op=D.optical[oi];
    $('timeline').value=si;$('timeinfo').textContent=`SAR F${sr.f} · ${Number(sr.t).toFixed(1)} ms | Optical F${op.f} · ${Number(op.t).toFixed(1)} ms | nominal timing only`;
    const [om,sm,gm]=await Promise.all([image(op.path),image(sr.path),image(sr.gray)]); if($('opticalImage')){$('opticalImage').src=om.src;fitCanvas($('opticalOverlay'),om.naturalWidth,om.naturalHeight);clearCanvas($('opticalOverlay'));if($('sourceBbox').checked)drawBoxes($('opticalOverlay'),(D.boxes[String(op.f)]||[]).map(b=>({geometry_type:'RECT',x1:b[0],y1:b[1],x2:b[2],y2:b[3]})),'#ffda6c');$('opticalMeta').textContent=`Native optical F${op.f}; source bbox ${(D.boxes[String(op.f)]||[]).length}`}
    if($('sarImage')){$('sarImage').src=sm.src;fitCanvas($('sarOverlay'),D.sar_width,D.sar_height);clearCanvas($('sarOverlay'));drawBoxes($('sarOverlay'),state.marks.filter(m=>m.frame_index===sr.f),'#ffdf64');if(refs)renderRefs();$('sarMeta').textContent=`Native SAR F${sr.f}; marks are observation geometry, not target boxes`}
    if($('grayImage'))$('grayImage').src=gm.src; if($('frameStart')&&!$('frameStart').value){$('frameStart').value=D.sar[0].f;$('frameEnd').value=D.sar.at(-1).f} renderLists();
  }
  function renderLists(){if($('markList'))$('markList').innerHTML=state.marks.map((m,i)=>`<div class="item"><button data-del-mark="${i}">×</button><b>${m.geometry_type}</b> · F${m.frame_index} · ${m.role}<br><span class="muted">${m.geometry_type==='POINT'?`(${m.x.toFixed(1)}, ${m.y.toFixed(1)})`:`[${m.x1.toFixed(1)},${m.y1.toFixed(1)}]→[${m.x2.toFixed(1)},${m.y2.toFixed(1)}]`}</span> ${m.note||''}</div>`).join('')||'<div class="muted">暂无 spatial mark</div>';if($('bookmarkList'))$('bookmarkList').innerHTML=state.bookmarks.map((b,i)=>`<div class="item"><button data-del-bookmark="${i}">×</button><b>${b.bookmark_type}</b> · F${b.sar_frame_index} ${b.note||''}</div>`).join('')||'<div class="muted">暂无 bookmark</div>';if($('revisionList'))$('revisionList').innerHTML=state.revisions.map(r=>`<div class="item"><b>r${r.revision} · ${r.observation_phase}</b> · ${r.created_at}<br>frames ${r.sar_frame_start}–${r.sar_frame_end}; marks ${r.spatial_marks.length}; certainty ${r.human_certainty}</div>`).join('')||'<div class="muted">尚未保存 revision</div>';document.querySelectorAll('[data-del-mark]').forEach(b=>b.onclick=()=>{state.marks.splice(+b.dataset.delMark,1);saveLocal();render()});document.querySelectorAll('[data-del-bookmark]').forEach(b=>b.onclick=()=>{state.bookmarks.splice(+b.dataset.delBookmark,1);saveLocal();render()});}
  function record(){const now=new Date().toISOString(),baseId=state.revisions[0]?.observation_id||D.event_hypothesis_id+'_OBS_'+Date.now();return{schema_version:'TPGT_OBSERVATION_RECORD_v0.1',observation_id:baseId,event_hypothesis_id:D.event_hypothesis_id,domain:D.domain,run_id:D.run_id,revision:(state.revisions.at(-1)?.revision||0)+1,observation_phase:mode==='OPEN_BOOK'?'POST_OPEN_BOOK':'PRE_OPEN_BOOK',view_mode:mode==='OPEN_BOOK'?'OPEN_BOOK':'BLIND_OBSERVATION',sar_frame_start:Number($('frameStart').value),sar_frame_end:Number($('frameEnd').value),spatial_marks:structuredClone(state.marks),morphology:checked('morphology'),transitions:checked('transitions'),continuity:$('continuity').value,human_certainty:$('certainty').value,bookmarks:structuredClone(state.bookmarks),observation_text:$('observationText').value,display_semantics:{sar_source:D.sar_source,gray_is_bgr2gray_derived:true},sync_semantics:D.sync_semantics,created_at:state.revisions[0]?.created_at||now,updated_at:now,provenance:{source_basis:'Phase 1A evidence pack',blind_revision_immutable:true}}}
  async function post(path,obj){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});return r.ok}catch(_){return false}}
  async function saveObservation(){const r=record();state.revisions.push(r);saveLocal();const ok=await post('../../api/records',r);$('saveStatus').textContent=ok?` 已写入 records/r${r.revision}`:' 已保存到当前浏览器（启动 serve_workbench.py 可写入 records）';renderLists()}
  function exportAll(){const blob=new Blob([JSON.stringify({schema:'TPGT_OBSERVATION_REVISION_SET_v0.1',event_hypothesis_id:D.event_hypothesis_id,revisions:state.revisions},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=D.event_hypothesis_id+'_observation_revisions.json';a.click();URL.revokeObjectURL(a.href)}
  function markDown(ev){if(mode==='OPEN_BOOK')return;const c=$('sarOverlay'),p=nativePoint(ev,c),kind=document.querySelector('input[name=drawMode]:checked')?.value||'RECT';if(kind==='POINT'){commitMark(kind,p,p);return}draw={kind,start:p,current:p};c.setPointerCapture?.(ev.pointerId);ev.preventDefault()}
  function markMove(ev){if(!draw||mode==='OPEN_BOOK')return;draw.current=nativePoint(ev,$('sarOverlay'));clearCanvas($('sarOverlay'));drawBoxes($('sarOverlay'),state.marks.filter(m=>m.frame_index===D.sar[si].f),'#ffdf64');const g=$('sarOverlay').getContext('2d');g.strokeStyle='#ffdf64';g.lineWidth=2;g.strokeRect(Math.min(draw.start.x,draw.current.x),Math.min(draw.start.y,draw.current.y),Math.abs(draw.current.x-draw.start.x),Math.abs(draw.current.y-draw.start.y))}
  function markUp(ev){if(!draw||mode==='OPEN_BOOK')return;const d=draw;draw=null;commitMark(d.kind,d.start,nativePoint(ev,$('sarOverlay')))}
  function commitMark(kind,s,p){const m={mark_id:D.event_hypothesis_id+'_M'+(state.marks.length+1).toString().padStart(3,'0'),geometry_type:kind==='POINT'?'POINT':'RECT',frame_index:D.sar[si].f,native_image_width:D.sar_width,native_image_height:D.sar_height,role:$('markRole')?.value||'STRUCTURE',note:''};if(kind==='POINT'){m.x=p.x;m.y=p.y}else{m.x1=Math.min(s.x,p.x);m.y1=Math.min(s.y,p.y);m.x2=Math.max(s.x,p.x);m.y2=Math.max(s.y,p.y);if(m.x2-m.x1<2||m.y2-m.y1<2)return}state.marks.push(m);saveLocal();render()}
  function addBookmark(){state.bookmarks.push({bookmark_type:$('bookmarkType').value,sar_frame_index:D.sar[si].f,note:$('bookmarkNote').value});$('bookmarkNote').value='';saveLocal();renderLists()}
  async function contactSheet(){const frames=[...new Map(state.bookmarks.sort((a,b)=>a.sar_frame_index-b.sar_frame_index).map(b=>[b.sar_frame_index,b])).values()];if(!frames.length){$('contactStatus').textContent='请先添加 bookmark';return}const imgs=[];for(const b of frames){const row=D.sar.find(x=>x.f===b.sar_frame_index);if(row)imgs.push([await image(row.path),b])}const w=420,h=300,cols=2,c=document.createElement('canvas');c.width=w*cols;c.height=h*Math.ceil(imgs.length/cols);const g=c.getContext('2d');g.fillStyle='#101820';g.fillRect(0,0,c.width,c.height);imgs.forEach(([im,b],i)=>{const x=i%cols*w,y=Math.floor(i/cols)*h;const s=Math.min((w-10)/im.naturalWidth,(h-42)/im.naturalHeight);g.drawImage(im,x+5,y+28,im.naturalWidth*s,im.naturalHeight*s);g.fillStyle='white';g.font='16px sans-serif';g.fillText(`${D.event_hypothesis_id} · F${b.sar_frame_index} · ${b.bookmark_type}`,x+6,y+20)});c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=D.event_hypothesis_id+'_observation_contact_sheet.jpg';a.click();URL.revokeObjectURL(a.href)});$('contactStatus').textContent='已生成，仅含 bookmark frame / observation 描述'}
  function renderRefs(){if(!refs)return;const c=$('sarOverlay');clearCanvas(c);drawBoxes(c,state.marks.filter(m=>m.frame_index===D.sar[si].f),'#ffdf64');for(const [key,on] of Object.entries(refs.toggles||{}))if(on)drawBoxes(c,(refs[key]||[]).filter(x=>x.frame_index===D.sar[si].f||x.sar_frame_index===D.sar[si].f).map(x=>x.geometry_type?x:{geometry_type:'RECT',x1:Number(x.cx)-Number(x.width)/2,y1:Number(x.cy)-Number(x.height)/2,x2:Number(x.cx)+Number(x.width)/2,y2:Number(x.cy)+Number(x.height)/2} ),key==='manual_reference'?'#ff5c78':key==='derived_reference'?'#59d9ff':'#c18cff')}
  async function loadOpenBook(){try{refs=await (await fetch('open_book_registry.json')).json();const oc=$('overlayControls');oc.innerHTML=Object.entries(refs.layers).map(([k,v])=>`<label><input type="checkbox" data-ref="${k}"> ${v.label} <span class="badge ${v.provenance_kind==='MANUAL'?'manual':'derived'}">${v.provenance_kind}</span></label>`).join('');refs.toggles={};oc.querySelectorAll('[data-ref]').forEach(x=>x.onchange=()=>{refs.toggles[x.dataset.ref]=x.checked;render()});$('referenceLegend').innerHTML=Object.values(refs.layers).map(v=>`<div class="item"><b>${v.label}</b> · ${v.provenance_kind} · ${v.source}</div>`).join('');$('identityAnnotations').innerHTML=(refs.identity_annotations||[]).map(x=>`<div class="item">${x.target_annotation_id||x.annotation_id||'identity'} · ${x.identity_semantics||''} · frames ${x.frame_start||''}–${x.frame_end||''}</div>`).join('')||'<div class="muted">暂无 registered identity annotation</div>';render()}catch(e){$('referenceLegend').textContent='Open-book resources unavailable: '+e}}
  $('timeline').min=0;$('timeline').max=D.sar.length-1;$('timeline').oninput=()=>{si=+$('timeline').value;render()};$('prev').onclick=()=>{si=Math.max(0,si-1);render()};$('next').onclick=()=>{si=Math.min(D.sar.length-1,si+1);render()};$('play').onclick=()=>{clearInterval(timer);timer=setInterval(()=>{if(si>=D.sar.length-1)return clearInterval(timer);si++;render()},1000/D.sar_fps/(+$('speed').value))};$('playBack').onclick=()=>{clearInterval(timer);timer=setInterval(()=>{if(si<=0)return clearInterval(timer);si--;render()},1000/D.sar_fps/(+$('speed').value))};$('pause').onclick=()=>clearInterval(timer);$('optPrev').onclick=()=>{oi=Math.max(0,oi-1);si=D.sar.reduce((b,x,i)=>Math.abs(x.t-D.optical[oi].t)<Math.abs(D.sar[b].t-D.optical[oi].t)?i:b,0);render()};$('optNext').onclick=()=>{oi=Math.min(D.optical.length-1,oi+1);si=D.sar.reduce((b,x,i)=>Math.abs(x.t-D.optical[oi].t)<Math.abs(D.sar[b].t-D.optical[oi].t)?i:b,0);render()};$('sourceBbox').onchange=render;if(mode!=='OPEN_BOOK'){$('sarOverlay').addEventListener('pointerdown',markDown);$('sarOverlay').addEventListener('pointermove',markMove);$('sarOverlay').addEventListener('pointerup',markUp)}$('addBookmark')?.addEventListener('click',addBookmark);$('contactSheet')?.addEventListener('click',contactSheet);$('saveObservation').onclick=saveObservation;$('exportObservation').onclick=exportAll;$('sourceCard')&&($('sourceCard').textContent=JSON.stringify(D.source_card,null,2));
  $('saveInterpretation')?.addEventListener('click',async()=>{const x={schema_version:'TPGT_INTERPRETATION_CANDIDATE_v0.1',observation_id:state.revisions.at(-1)?.observation_id||null,event_hypothesis_id:D.event_hypothesis_id,interpretation_text:$('interpretationText').value,possible_hypotheses:$('possibleHypotheses').value,observed_agreement_disagreement_with_reference:$('referenceAgreement').value,ambiguity:$('interpretationAmbiguity').value,additional_evidence_needed:$('additionalEvidence').value,created_at:new Date().toISOString()};const ok=await post('../../api/interpretations',x);$('interpretationStatus').textContent=ok?'已写入 interpretations':'已保存在当前页面会话；启动 server 可落盘'});
  $('importObservation')?.addEventListener('change',async ev=>{const f=ev.target.files[0];if(!f)return;const x=JSON.parse(await f.text());state.revisions.push(...(x.revisions||[x]));saveLocal();renderLists()});$('identityImport')?.addEventListener('change',async ev=>{const x=JSON.parse(await ev.target.files[0].text());refs=refs||{};refs.identity_annotations=[...(refs.identity_annotations||[]),...(Array.isArray(x)?x:[x])];$('identityAnnotations').innerHTML=refs.identity_annotations.map(a=>`<div class="item">${a.target_annotation_id||a.annotation_id} · ${a.identity_semantics||''}</div>`).join('')});
  $('title').textContent=(mode==='OPEN_BOOK'?'OPEN_BOOK_VIEW · ':'OBSERVATION_VIEW · ')+D.title;
  if(mode==='OPEN_BOOK')loadOpenBook();render();
})();
